config/routes.rb
Classroom::Application.routes.draw do
  root :to => "sessions#new"
  resources :charts 
  resources :users
  resource :session
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
end

app/models/chart.rb
class Chart < ActiveRecord::Base
belongs_to :user
has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
belongs_to :chart
end

app/models/profile.rb
class Profile < ActiveRecord::Base

belongs_to :user
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
attr_accessor :password
validates :email, :uniqueness => true, 
		:length => { :within => 5..50 },
		  :format => { :with => /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i } 	
validates :password, :confirmation => true,
                       :length => { :within => 4..20 },
                       :presence => true,
                       :if => :password_required?
             

#has_one :profile

has_many :replies, :through => :charts, :source => :comments
 before_save :encrypt_new_password

  def self.authenticate(email, password)
    user = find_by_email(email)
    return user if user && user.authenticated?(password)
  end

  def authenticated?(password)
    self.hashed_password == encrypt(password)
  end

  protected
    def encrypt_new_password
      return if password.blank?
      self.hashed_password = encrypt(password)
    end

    def password_required?
      hashed_password.blank? || password.present?
    end

    def encrypt(string)
      Digest::SHA1.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
protect_from_forgery


protected 
    # Returns the currently logged in user or nil if there isn't one
    def current_user
      return unless session[:user_id]
      @current_user ||= User.find_by_id(session[:user_id]) 
    end

    # Make current_user available in templates as a helper
    helper_method :current_user

    # Filter method to enforce a login requirement
    # Apply as a before_filter on any controller you want to protect
    def authenticate
      logged_in? ? true : access_denied
    end

    # Predicate method to test for a logged in user    
    def logged_in?
      current_user.is_a? User
    end

    # Make logged_in? available in templates as a helper
    helper_method :logged_in?

    def access_denied
      redirect_to login_path, :notice => "Please log in to continue" and return false
    end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
before_filter :authenticate, :except => [:index, :show]  
# GET /charts
  # GET /charts.xml
  def index
    @charts = Chart.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @charts }
    end
  end

  # GET /charts/1
  # GET /charts/1.xml
  def show
    @chart = Chart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @chart }
    end
  end

  # GET /charts/new
  # GET /charts/new.xml
  def new
    @chart = Chart.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @chart }
    end
  end

  # GET /charts/1/edit
  def edit
    @chart = Chart.find(params[:id])
  end

  # POST /charts
  # POST /charts.xml
  def create
    @chart = Chart.new(params[:chart])

    respond_to do |format|
      if @chart.save
        format.html { redirect_to(@chart, :notice => 'Chart was successfully created.') }
        format.xml  { render :xml => @chart, :status => :created, :location => @chart }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @chart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /charts/1
  # PUT /charts/1.xml
  def update
    @chart = Chart.find(params[:id])

    respond_to do |format|
      if @chart.update_attributes(params[:chart])
        format.html { redirect_to(@chart, :notice => 'Chart was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @chart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /charts/1
  # DELETE /charts/1.xml
  def destroy
    @chart = Chart.find(params[:id])
    @chart.destroy

    respond_to do |format|
      format.html { redirect_to(charts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_chart

  def create
    @comment = @chart.comments.new(params[:comment])
    if @comment.save
      redirect_to @chart, :notice => 'Thanks for your comment'
    else
      redirect_to @chart, :alert => 'Unable to add comment'
    end
  end

  def destroy
    @comment = @chart.comments.find(params[:id])
    @comment.destroy
    redirect_to @chart, :notice => 'Comment deleted'
  end

  private
    def load_chart
      @chart = Chart.find(params[:chart_id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


def create
 if user = User.authenticate(params[:email], params[:password])
  session[:user_id] = user.id
  redirect_to charts_path, :notice => "Logged in Successfully" 
   else
    flash.now[:alert] = "Invalid login/password combination"
     render :action => 'new'
	end
  end	
def destroy
	reset_session
	redirect_to login_path, :notice => "you successfully logged out"	
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def new
   @user = User.new
 end

 def create
   @user = User.new(params[:user])
   if @user.save
     redirect_to login_path, :notice => 'User successfully added.'
   else
     render :action => 'new'
   end
 end

 def edit
   @user = User.find(params[:id])
 end

 def update
   @user = User.find(params[:id])
   if @user.update_attributes(params[:user])
     redirect_to login_path, :notice => 'Updated user information
successfully.'
   else
     render :action => 'edit'
   end
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
def default_text(text)  
     onFocusFunction = "field = event.target || event.srcElement; if (field.value=='#{text}') {field.value = '';}else {return false}"  
     onBlurFunction = "field = event.target || event.srcElement; if (field.value=='') {field.value = '#{text}';}else {return false}"  
     {:value => text, :onfocus => onFocusFunction, :onblur => onBlurFunction}   
end
end

app/helpers/charts_helper.rb
module ChartsHelper
def default_text(text)  
     onFocusFunction = "field = event.target || event.srcElement; if (field.value=='#{text}') {field.value = '';}else {return false}"  
     onBlurFunction = "field = event.target || event.srcElement; if (field.value=='') {field.value = '#{text}';}else {return false}"  
     {:value => text, :onfocus => onFocusFunction, :onblur => onBlurFunction}   
end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charts/_chart.html.erb
<%= div_for chart do %>
  <h3>
    <%= link_to chart.snumber, chart %>
    <span class='actions'>
      <%= link_to "Edit", edit_article_path(chart) %>
      <%= link_to "Delete", chart, :confirm => "Are you sure?", :method => :delete %>
    </span>
  </h3>
  <%= chart.body %>
<% end %>

app/views/charts/_form.html.erb
<head>
<style type="text/css">
.textb {position:absolute; margin-top:120px; margin-left:50px;}
.textb1 {position:absolute; margin-top:100px; margin-left:50px;}
.textb3 {position:absolute; margin-top:50px; margin-left:50px;}
.sub {position:absolute; margin-top:170px; margin-left:50px;}
</style>
</head>
<%= form_for(@chart) do |f| %>
  <% if @chart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chart.errors.count, "error") %> prohibited this chart from being saved:</h2>

      <ul>
      <% @chart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="textb3">
  <p>
  <i><b>Seat Number:</b></i>
  <i><b><%= @chart.snumber %></b></i>
  </p>
  </div>

    <div class="field">
    <b><i class="textb1"><%= f.label :Enter_Your_Name %></i></b><br />
    <div class="textb"><%= f.text_field :name, default_text("Empty...")%></div>
  </div>
  <div class="sub">
  <div class="actions">
    <%= f.submit %>
   </div>
  </div>
<% end %>

app/views/charts/edit.html.erb
<head>
<style type="text/css">
.pos {position:absolute; margin-top:210px; margin-left:50px;}
</style>
</head>
<h1 align="center">Edit chart to Reserve Seat</h1>
<hr></hr>
<%= render 'form' %>
<div class="pos">
<%= link_to 'Show', @chart %> |
<%= link_to 'Back', charts_path %>
</div>

app/views/charts/index.html.erb
<html>
<head>
<style type="text/css">
.table1 {border-width: 1px; position:absolute; margin-top:200px; margin-left:30px; width:10%; min-width:20px; max-width:80px;}
.table2 {border-width: 1px; position:absolute; margin-top:200px; margin-left:180px; width:10%; min-width:20px; max-width:80px;}
.table3 {border-width: 1px; position:absolute; margin-top:200px; margin-left:330px; width:10%; min-width:20px; max-width:80px;}
.table4 {border-width: 1px; position:absolute; margin-top:200px; margin-left:470px; width:10%; min-width:20px; max-width:80px;}
.table5 {border-width: 1px; position:absolute; margin-top:200px; margin-left:680px; width:10%; min-width:20px; max-width:80px;}
.table6 {border-width: 1px; position:absolute; margin-top:200px; margin-left:830px; width:10%; min-width:20px; max-width:80px;}
.table7 {border-width: 1px; position:absolute; margin-top:200px; margin-left:980px; width:10%; min-width:20px; max-width:80px;}
.table8 {border-width: 1px; position:absolute; margin-top:200px; margin-left:1120px; width:10%; min-width:20px; max-width:80px;}
.table9 {border-width: 1px; position:absolute; margin-top:300px; margin-left:30px; width:10%; min-width:20px; max-width:80px;}
.table10 {border-width: 1px; position:absolute; margin-top:300px; margin-left:180px; width:10%; min-width:20px; max-width:80px;}
.table11 {border-width: 1px; position:absolute; margin-top:300px; margin-left:330px; width:10%; min-width:20px; max-width:80px;}
.table12 {border-width: 1px; position:absolute; margin-top:300px; margin-left:470px; width:10%; min-width:20px; max-width:80px;}
.table13 {border-width: 1px; position:absolute; margin-top:300px; margin-left:680px; width:10%; min-width:20px; max-width:80px;}
.table14 {border-width: 1px; position:absolute; margin-top:300px; margin-left:830px; width:10%; min-width:20px; max-width:80px;}
.table15 {border-width: 1px; position:absolute; margin-top:300px; margin-left:980px; width:10%; min-width:20px; max-width:80px;}
.table16 {border-width: 1px; position:absolute; margin-top:300px; margin-left:1120px; width:10%; min-width:20px; max-width:80px;}
.table17 {border-width: 1px; position:absolute; margin-top:400px; margin-left:30px; width:10%; min-width:20px; max-width:80px;}
.table18 {border-width: 1px; position:absolute; margin-top:400px; margin-left:180px; width:10%; min-width:20px; max-width:80px;}
.table19 {border-width: 1px; position:absolute; margin-top:400px; margin-left:330px; width:10%; min-width:20px; max-width:80px;}
.table20 {border-width: 1px; position:absolute; margin-top:400px; margin-left:470px; width:10%; min-width:20px; max-width:80px;}
.table21 {border-width: 1px; position:absolute; margin-top:400px; margin-left:680px; width:10%; min-width:20px; max-width:80px;}
.table22 {border-width: 1px; position:absolute; margin-top:400px; margin-left:830px; width:10%; min-width:20px; max-width:80px;}
.table23 {border-width: 1px; position:absolute; margin-top:400px; margin-left:980px; width:10%; min-width:20px; max-width:80px;}
.table24 {border-width: 1px; position:absolute; margin-top:400px; margin-left:1120px; width:10%; min-width:20px; max-width:80px;}
.table25 {border-width: 1px; position:absolute; margin-top:500px; margin-left:30px; width:10%; min-width:20px; max-width:80px;}
.table26 {border-width: 1px; position:absolute; margin-top:500px; margin-left:180px; width:10%; min-width:20px; max-width:80px;}
.table27 {border-width: 1px; position:absolute; margin-top:500px; margin-left:330px; width:10%; min-width:20px; max-width:80px;}
.table28 {border-width: 1px; position:absolute; margin-top:500px; margin-left:470px; width:10%; min-width:20px; max-width:80px;}
.table29 {border-width: 1px; position:absolute; margin-top:500px; margin-left:680px; width:10%; min-width:20px; max-width:80px;}
.table30 {border-width: 1px; position:absolute; margin-top:500px; margin-left:830px; width:10%; min-width:20px; max-width:80px;}
.table31 {border-width: 1px; position:absolute; margin-top:500px; margin-left:980px; width:10%; min-width:20px; max-width:80px;}
.table32 {border-width: 1px; position:absolute; margin-top:500px; margin-left:1120px; width:10%; min-width:20px; max-width:80px;}
.prof {position:absolute; left:560px; top:130px;}
.log {position:absolute; left:100px; top:60px;}
.heroku {position:absolute; left:900px; top:80px; font-family:"Times New Roman", Times, serif; font-size:20px;}
</style>
</head>
<div align="center">
<p><h1> CS-408 CLASSROOM SEATING CHART<h1></p>
<hr> </hr>
</div>
<div class="prof">
<p><h2> Prof. Kenytt Avery <h2><p>
</div>
<div class="table1">
  <table border="1">
<% chart = Chart.find(3) %>
    <th><%= chart.snumber %></th>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
   </table>
</div>
<div class="table2">
  <table border="1">
<% chart = Chart.find(4) %>
    <th><%= chart.snumber %></th>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </table>
</div>
<div class="table3">
  <table border="1">
<% chart = Chart.find(5) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table4">
  <table border="1">
<% chart = Chart.find(6) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table5">
  <table border="1">
<% chart = Chart.find(7) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table6">
  <table border="1">
<% chart = Chart.find(8) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table7">
  <table border="1">
<% chart = Chart.find(9) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table8">
  <table border="1">
<% chart = Chart.find(10) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table9">
  <table border="1">
<% chart = Chart.find(11) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table10">
  <table border="1">
<% chart = Chart.find(12) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table11">
  <table border="1">
<% chart = Chart.find(14) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table12">
  <table border="1">
<% chart = Chart.find(15) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table13">
  <table border="1">
<% chart = Chart.find(16) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table14">
  <table border="1">
<% chart = Chart.find(17) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table15">
  <table border="1">
<% chart = Chart.find(18) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table16">
  <table border="1">
<% chart = Chart.find(19) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table17">
  <table border="1">
<% chart = Chart.find(20) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table18">
  <table border="1">
<% chart = Chart.find(21) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table19">
  <table border="1">
<% chart = Chart.find(22) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table20">
  <table border="1">
<% chart = Chart.find(23) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table21">
  <table border="1">
<% chart = Chart.find(24) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table22">
  <table border="1">
<% chart = Chart.find(25) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table23">
  <table border="1">
<% chart = Chart.find(26) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table24">
  <table border="1">
<% chart = Chart.find(27) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table25">
  <table border="1">
<% chart = Chart.find(28) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table26">
  <table border="1">
<% chart = Chart.find(29) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table27">
  <table border="1">
<% chart = Chart.find(30) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table28">
  <table border="1">
<% chart = Chart.find(31) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table29">
  <table border="1">
<% chart = Chart.find(32) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table30">
  <table border="1">
<% chart = Chart.find(33) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table31">
  <table border="1">
<% chart = Chart.find(34) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="table32">
  <table border="1">
<% chart = Chart.find(35) %>
    <tr>
    <th><%= chart.snumber %></th>
    </tr>
    <tr>
    <td bgcolor="#33FF00"><%= chart.name %></td>
    <td><%= link_to 'Reserve', chart %></td>
    </tr>
    </tr>
</table>
</div>
<div class="log">
<h2><%= link_to 'Logout', logout_path %></h2>
</div>
<div class="heroku">
<a href="http://vivid-lightning-479.heroku.com/" target="_blank">Want to chat with your classmates? Click here!</a>
<div>
</html>

app/views/charts/new.html.erb
<h1>New chart</h1>

<%= render 'form' %>

<%= link_to 'Back', charts_path %>

app/views/charts/show.html.erb
<head>
<style type="text/css">
.pos {position:absolute; margin-top:60px; margin-left:60px;}
.pos1 {position:absolute; margin-top:110px; margin-left:60px;}
.pos2 {position:absolute; margin-top:170px; margin-left:60px;}
.pos3 {position:absolute; margin-top:225px; margin-left:60px;}

</style>

</head>

<p><h1 align="center"> Your Reserved/Canceled Seat </h1></p>
<hr></hr>
<div class="pos">
<p><h3>
  <u><i>Seat Number:</i></u>
  <i><%= @chart.snumber %></i>
</h3></p>
</div>
<div class="pos1">
<p><h3>
  <u><i>Name:</i></u>
  <i><%= @chart.name %></i>
</h3></p>
</div>
<div class="pos2">
<h3><%= link_to 'Edit', edit_chart_path(@chart) %> |
<%= link_to 'Back', charts_path %></h3>
</div>
<div class="pos3">
<h3><p id="notice"><%= notice %></p></h3>
</div>

app/views/charts/shown.html.erb
<%= render @chart %>

<h3>Comments</h3>
<div id="comments">
  <%= render @chart.comments %>
</div>

<%= render :file => 'comments/new' %>

app/views/comments/_comment.html.erb
<%= div_for comment do %>
  <h3>
    <%= comment.name %> &lt;<%= comment.email %>&gt; said:
    <span class='actions'>
      <%= link_to 'Delete', chart_comment_path(:chart_id => @chart, :id => comment), :confirm => 'Are you sure?', :method => :delete %>
    </span>
  </h3>
  <%= comment.body %>
<% end %>

app/views/comments/new.html.erb
<%= form_for([@chart, @chart.comments.new]) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit 'Add' %>
  </div>
<% end %

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Classroom</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Back', login_path %>

app/views/users/new.html.erb
<head>
<style type="text/css">
.table1 {margin-top:70px;}
h1{font-family:"Times New Roman", Times, serif; font-size:35px;}
.table8 {position:absolute; width:200px; margin-top:305px; margin-left:50px; font-family:"Times New Roman", Times, serif; font-size:25px; }
</style>
</head>
<div class="table1">
<h1>New user</h1>
</div>
<%= render 'form' %>

<!--%= link_to 'Back', charts_path %-->
<div class="table8">
<%= link_to 'View Chart', charts_path %>
<p> Click the above link to view the seating chart of CS 408.</p>
</div>